version: '3.8'
services:
  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
  tests:
    build: .
    environment:
      executeType: remote
      seleniumHubUrl: http://selenium:4444/wd/hub
    depends_on:
      - selenium
    command: mvn clean test
